name: Deploy p5.js to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # 루트에 있는 HTML, JS, CSS 포함

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4